In [ ]:
#A1. Write your own functions for the following modules:
# a) Summation unit
# b) Activation Unit – Step, Bipolar Step, Sigmoid, TanH, ReLU and Leaky ReLU functions
# c) Comparator unit for Error calculation

import math

def summation_unit(inputs, weights):
    return sum(i * w for i, w in zip(inputs, weights))

def step_function(x):
    return 1 if x >= 0 else 0

def bipolar_step_function(x):
    return 1 if x >= 0 else -1

def sigmoid_function(x):
    return 1 / (1 + math.exp(-x))

def tanh_function(x):
    return math.tanh(x)

def relu_function(x):
    return max(0, x)

def leaky_relu_function(x):
    return x if x >= 0 else 0.01 * x

def comparator_unit(predicted, actual):
    return actual - predicted


In [ ]:
# A2. Develop the above perceptron in your own code (don’t use the perceptron model available from
# package). Use the initial weights as provided below.

def train_perceptron_and_gate(inputs, outputs, epochs=1000, lr=0.05):
    weights = [10, 0.2, -0.75]
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(inputs)):
            summation = summation_unit([1] + inputs[i], weights)
            prediction = step_function(summation)
            error = comparator_unit(prediction, outputs[i])
            total_error += error ** 2
            for j in range(len(weights)):
                weights[j] += lr * error * ([1] + inputs[i])[j]
        if total_error <= 0.002:
            break
    return weights, epoch

inputs = [[0, 0], [0, 1], [1, 0], [1, 1]]
outputs = [0, 0, 0, 1]
weights, epochs = train_perceptron_and_gate(inputs, outputs)
print("Weights:", weights)
print("Epochs:", epochs)


Weights: [-0.10000000000000765, 0.1000000000000001, 0.05000000000000032]
Epochs: 129


In [ ]:
# A3. Repeat the above A1 experiment with following activation functions

def train_with_activation(inputs, outputs, activation_func, epochs=1000, lr=0.05):
    weights = [10, 0.2, -0.75]
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(inputs)):
            summation = summation_unit([1] + inputs[i], weights)
            prediction = activation_func(summation)
            error = comparator_unit(prediction, outputs[i])
            total_error += error ** 2
            for j in range(len(weights)):
                weights[j] += lr * error * ([1] + inputs[i])[j]
        if total_error <= 0.002:
            break
    return weights, epoch

# Example using Sigmoid Function
inputs = [[0, 0], [0, 1], [1, 0], [1, 1]] # Define inputs and outputs here
outputs = [0, 0, 0, 1]
weights, epochs = train_with_activation(inputs, outputs, sigmoid_function)

print("Weights:", weights)
print("Epochs:", epochs)


Weights: [-6.1353130787344305, 3.970833206406072, 3.963948347259991]
Epochs: 999


In [10]:
# A4. Repeat exercise A1 with varying the learning rate, keeping the initial weights same.

def train_perceptron_and_gate(inputs, outputs, epochs=1000, lr=0.05): # Added the function definition back
    weights = [10, 0.2, -0.75]
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(inputs)):
            summation = summation_unit([1] + inputs[i], weights)
            prediction = step_function(summation)
            error = comparator_unit(prediction, outputs[i])
            total_error += error ** 2
            for j in range(len(weights)):
                weights[j] += lr * error * ([1] + inputs[i])[j]
        if total_error <= 0.002:
            break
    return weights, epoch

learning_rates = [0.1 * i for i in range(1, 11)]
iterations = []
inputs = [[0, 0], [0, 1], [1, 0], [1, 1]]  # Define inputs and outputs here
outputs = [0, 0, 0, 1]

for lr in learning_rates:
    _, epoch = train_perceptron_and_gate(inputs, outputs, lr=lr)
    iterations.append(epoch)

    print(f"Learning Rate: {lr}, Epochs: {epoch}")



Learning Rate: 0.1, Epochs: 67
Learning Rate: 0.2, Epochs: 36
Learning Rate: 0.30000000000000004, Epochs: 22
Learning Rate: 0.4, Epochs: 22
Learning Rate: 0.5, Epochs: 18
Learning Rate: 0.6000000000000001, Epochs: 18
Learning Rate: 0.7000000000000001, Epochs: 14
Learning Rate: 0.8, Epochs: 13
Learning Rate: 0.9, Epochs: 12
Learning Rate: 1.0, Epochs: 11


In [13]:
# A5. Repeat the above exercises, A1 to A3, for XOR gate logic.

inputs_xor = [[0, 0], [0, 1], [1, 0], [1, 1]]
outputs_xor = [0, 1, 1, 0]
weights, epochs = train_perceptron_and_gate(inputs_xor, outputs_xor)
print("Weights:", weights)
print("Epochs:", epochs)

Weights: [0.09999999999999236, -0.09999999999999969, -0.09999999999999969]
Epochs: 999


In [15]:
# A6. Use customer data provided below.

def train_perceptron_customers(data, labels, epochs=1000, lr=0.05):
    weights = [0.1, 0.2, 0.3, 0.4]  # Example initial weights
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(data)):
            summation = summation_unit([1] + data[i], weights)
            prediction = sigmoid_function(summation)
            error = comparator_unit(prediction, labels[i])
            total_error += error ** 2
            for j in range(len(weights)):
                weights[j] += lr * error * ([1] + data[i])[j]
        if total_error <= 0.002:
            break
    return weights, epoch

customer_data = [
    [20, 6, 2],
    [16, 3, 6],
    [27, 6, 2],
    [19, 1, 2],
    [24, 4, 2],
    [22, 1, 5],
    [15, 4, 2],
    [18, 4, 2],
    [21, 1, 4],
    [16, 2, 4]
]

high_value_labels = [1, 1, 1, 0, 1, 0, 1, 1, 0, 0]

weights, epochs = train_perceptron_customers(customer_data, high_value_labels)

print("Weights:", weights)
print("Epochs:", epochs)

Weights: [-0.18250271389279019, -1.3365214891771673, 9.012435167930922, -0.0533006109983556]
Epochs: 122


In [16]:
# A7. Compare the results obtained from above perceptron learning to the ones obtained with matrix
# pseudo-inverse

import numpy as np

def pseudo_inverse_solution(data, labels):
    X = np.array([[1] + d for d in data])
    Y = np.array(labels)
    pseudo_inv = np.linalg.pinv(X)
    weights = np.dot(pseudo_inv, Y)
    return weights

weights_pseudo = pseudo_inverse_solution(customer_data, high_value_labels)
print("Pseudo-Inverse Weights:", weights_pseudo)

Pseudo-Inverse Weights: [ 0.1139903  -0.02342675  0.2607237   0.03727212]


In [18]:
# A8. Develop the below Neural Network. Use learning rate (α) = 0.05 with a Sigmoid activation function.

def sigmoid_derivative(x):
    return x * (1 - x)

def train_nn_and_gate(inputs, outputs, epochs=1000, lr=0.05):
    weights_input_hidden = [0.5, -0.6, 0.2]
    weights_hidden_output = [0.4, -0.7]
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(inputs)):
            hidden_input = summation_unit([1] + inputs[i], weights_input_hidden)
            hidden_output = sigmoid_function(hidden_input)
            output_input = summation_unit([1, hidden_output], weights_hidden_output)
            output = sigmoid_function(output_input)
            error = comparator_unit(output, outputs[i])
            total_error += error ** 2
            delta_output = error * sigmoid_derivative(output)
            delta_hidden = delta_output * sigmoid_derivative(hidden_output) * weights_hidden_output[1]
            weights_hidden_output[0] += lr * delta_output * 1
            weights_hidden_output[1] += lr * delta_output * hidden_output
            for j in range(len(weights_input_hidden)):
                weights_input_hidden[j] += lr * delta_hidden * ([1] + inputs[i])[j]
        if total_error <= 0.002:
            break
    return weights_input_hidden, weights_hidden_output, epoch

weights_input_hidden, weights_hidden_output, epochs = train_nn_and_gate(inputs, outputs)
print("Weights Input to Hidden:", weights_input_hidden)
print("Weights Hidden to Output:", weights_hidden_output)
print("Epochs:", epochs)

Weights Input to Hidden: [1.065546038523148, -1.6039201646705568, -1.103603376806378]
Weights Hidden to Output: [0.05922996021700995, -2.45894383324324]
Epochs: 999


In [19]:
# A9. Repeat the above A1 experiment for XOR Gate logic. Keep the learning rate & activation function
# same as A1

weights_input_hidden, weights_hidden_output, epochs = train_nn_and_gate(inputs_xor, outputs_xor)
print("Weights Input to Hidden:", weights_input_hidden)
print("Weights Hidden to Output:", weights_hidden_output)
print("Epochs:", epochs)

Weights Input to Hidden: [0.5616681385599502, -0.5607471249996671, 0.3093566144322304]
Weights Hidden to Output: [0.40664727753188135, -0.6764470646287483]
Epochs: 999


In [21]:
# A10. Repeat exercise A1 & A2 with 2 output nodes (as shown below).

def train_perceptron_2_outputs(inputs, outputs, epochs=1000, lr=0.05):
    weights = [[0.1, 0.2, -0.1], [0.05, 0.3, -0.25]]
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(inputs)):
            summation_1 = summation_unit([1] + inputs[i], weights[0])
            summation_2 = summation_unit([1] + inputs[i], weights[1])
            prediction_1 = step_function(summation_1)
            prediction_2 = step_function(summation_2)
            error_1 = comparator_unit(prediction_1, outputs[i][0])
            error_2 = comparator_unit(prediction_2, outputs[i][1])
            total_error += error_1 ** 2 + error_2 ** 2
            for j in range(len(weights[0])):
                weights[0][j] += lr * error_1 * ([1] + inputs[i])[j]
                weights[1][j] += lr * error_2 * ([1] + inputs[i])[j]
        if total_error <= 0.002:
            break
    return weights, epoch

outputs_2 = [[1, 0], [1, 0], [1, 0], [0, 1]]  # Example for AND Gate logic
weights, epochs = train_perceptron_2_outputs(inputs, outputs_2)
print("Weights:", weights)
print("Epochs:", epochs)

Weights: [[0.10000000000000002, -0.09999999999999999, -0.10000000000000002], [-0.2, 0.15000000000000002, 0.04999999999999999]]
Epochs: 9


In [22]:
# A11. Learn using a MLP network from Sci-Kit manual available.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


from sklearn.neural_network import MLPClassifier

# AND Gate using MLPClassifier
mlp_and = MLPClassifier(hidden_layer_sizes=(), activation='logistic', solver='sgd', max_iter=1000)
mlp_and.fit(inputs, outputs)
and_predictions = mlp_and.predict(inputs)

# XOR Gate using MLPClassifier
mlp_xor = MLPClassifier(hidden_layer_sizes=(), activation='logistic', solver='sgd', max_iter=1000)
mlp_xor.fit(inputs_xor, outputs_xor)
xor_predictions = mlp_xor.predict(inputs_xor)

# Print the predictions
print("AND Gate Predictions:")
print(and_predictions)

print("\nXOR Gate Predictions:")
print(xor_predictions)



AND Gate Predictions:
[0 0 0 0]

XOR Gate Predictions:
[0 0 1 1]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [24]:
# customer data
mlp_project = MLPClassifier(hidden_layer_sizes=(5,), activation='logistic', solver='sgd', max_iter=1000)
mlp_project.fit(customer_data, high_value_labels)
project_predictions = mlp_project.predict(customer_data)

# Print the predictions
print("Customer Data Predictions:")
print(project_predictions)

Customer Data Predictions:
[1 1 1 1 1 1 1 1 1 1]


In [25]:
# A12. Use the MLPClassifier() function on your project dataset.

def load_project_data(file_path):
    df = pd.read_excel(file_path)
    X = df.iloc[:, :-1].values  # Assuming the last column is the target variable
    y = df.iloc[:, -1].values   # Target column (assumed to be the last one)
    return X, y

# AND Gate Example (A2)
print("Training Perceptron for AND Gate Logic...")
inputs = [[0, 0], [0, 1], [1, 0], [1, 1]]
outputs = [0, 0, 0, 1]
weights, epochs = train_perceptron_and_gate(inputs, outputs)
print(f"Weights after training: {weights}")
print(f"Epochs to converge: {epochs}\n")
# XOR Gate Example (A5)
print("Training Perceptron for XOR Gate Logic...")
inputs_xor = [[0, 0], [0, 1], [1, 0], [1, 1]]
outputs_xor = [0, 1, 1, 0]
weights_xor, epochs_xor = train_perceptron_and_gate(inputs_xor, outputs_xor)
print(f"Weights after training for XOR: {weights_xor}")
print(f"Epochs to converge: {epochs_xor}\n")
# Customer Data Example (A6)
print("Training Perceptron for Customer Data...")
customer_data = [
    [20, 6, 2],
    [16, 3, 6],
    [27, 6, 2],
    [19, 1, 2],
    [24, 4, 2],
    [22, 1, 5],
    [15, 4, 2],
    [18, 4, 2],
    [21, 1, 4],
    [16, 2, 4]
]
high_value_labels = [1, 1, 1, 0, 1, 0, 1, 1, 0, 0]
weights_customers, epochs_customers = train_perceptron_customers(customer_data, high_value_labels)
print(f"Weights after training customer data: {weights_customers}")
print(f"Epochs to converge: {epochs_customers}\n")
# Comparing with Matrix Pseudo-Inverse (A7)
print("Comparing Weights with Pseudo-Inverse Method...")
weights_pseudo = pseudo_inverse_solution(customer_data, high_value_labels)
print(f"Weights from pseudo-inverse: {weights_pseudo}\n")
# Neural Network for AND Gate (A8)
print("Training Neural Network for AND Gate...")
weights_input_hidden, weights_hidden_output, epochs_nn = train_nn_and_gate(inputs, outputs)
print(f"Weights (input-hidden) after training: {weights_input_hidden}")
print(f"Weights (hidden-output) after training: {weights_hidden_output}")
print(f"Epochs to converge: {epochs_nn}\n")
# Neural Network for XOR Gate (A9)
print("Training Neural Network for XOR Gate...")
weights_input_hidden_xor, weights_hidden_output_xor, epochs_nn_xor = train_nn_and_gate(inputs_xor, outputs_xor)
print(f"Weights (input-hidden) after training XOR: {weights_input_hidden_xor}")
print(f"Weights (hidden-output) after training XOR: {weights_hidden_output_xor}")
print(f"Epochs to converge: {epochs_nn_xor}\n")
# Perceptron with 2 Output Nodes (A10)
print("Training Perceptron with 2 Output Nodes for AND Gate...")
outputs_2 = [[1, 0], [1, 0], [1, 0], [0, 1]]
weights_2_outputs, epochs_2_outputs = train_perceptron_2_outputs(inputs, outputs_2)
print(f"Weights for output 1 after training: {weights_2_outputs[0]}")
print(f"Weights for output 2 after training: {weights_2_outputs[1]}")
print(f"Epochs to converge: {epochs_2_outputs}\n")
# Using MLPClassifier for AND Gate (A11)
print("Using MLPClassifier for AND Gate...")
mlp_and = MLPClassifier(hidden_layer_sizes=(), activation='logistic', solver='sgd', max_iter=1000)
mlp_and.fit(inputs, outputs)
and_predictions = mlp_and.predict(inputs)
print(f"Predictions for AND Gate using MLPClassifier: {and_predictions}\n")
# Using MLPClassifier for XOR Gate (A11)
print("Using MLPClassifier for XOR Gate...")
mlp_xor = MLPClassifier(hidden_layer_sizes=(), activation='logistic', solver='sgd', max_iter=1000)
mlp_xor.fit(inputs_xor, outputs_xor)
xor_predictions = mlp_xor.predict(inputs_xor)
print(f"Predictions for XOR Gate using MLPClassifier: {xor_predictions}\n")


Training Perceptron for AND Gate Logic...
Weights after training: [-0.10000000000000765, 0.1000000000000001, 0.05000000000000032]
Epochs to converge: 129

Training Perceptron for XOR Gate Logic...
Weights after training for XOR: [0.09999999999999236, -0.09999999999999969, -0.09999999999999969]
Epochs to converge: 999

Training Perceptron for Customer Data...
Weights after training customer data: [-0.18250271389279019, -1.3365214891771673, 9.012435167930922, -0.0533006109983556]
Epochs to converge: 122

Comparing Weights with Pseudo-Inverse Method...
Weights from pseudo-inverse: [ 0.1139903  -0.02342675  0.2607237   0.03727212]

Training Neural Network for AND Gate...
Weights (input-hidden) after training: [1.065546038523148, -1.6039201646705568, -1.103603376806378]
Weights (hidden-output) after training: [0.05922996021700995, -2.45894383324324]
Epochs to converge: 999

Training Neural Network for XOR Gate...
Weights (input-hidden) after training XOR: [0.5616681385599502, -0.56074712499

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [32]:
# A12

import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder

df = pd.read_excel('/content/TRAINING_DATA.xlsx')

# Spliting the data into feature data (X) and target variable (y)
X = df.iloc[:, :-1].values  # Assuming the last column is the target variable
y = df.iloc[:, -1].values   # Target column (assumed to be the last one)

print(f"Data shape: {X.shape}, Labels shape: {y.shape}\n")

# Initializig LabelEncoder
label_encoder = LabelEncoder()

# Fitting and transform the target variable to have discrete class labels
y = label_encoder.fit_transform(y)

# Training an MLPClassifier on the project data
mlp_project = MLPClassifier(hidden_layer_sizes=(5,), activation='logistic', solver='sgd', max_iter=1000)
mlp_project.fit(X, y)

# Making predictions on the project data
project_predictions = mlp_project.predict(X)

# Printing the predictions
print(f"Predictions for Project Data using MLPClassifier\n {project_predictions}")

Data shape: (1126, 384), Labels shape: (1126,)

Predictions for Project Data using MLPClassifier
 [51 51 51 ... 51 51 51]
